# controller_manager:
#   ros__parameters:
#     update_rate: 100  # Hz

#     joint_state_broadcaster:
#       type: joint_state_broadcaster/JointStateBroadcaster

#     forward_position_controllers:
#       type: forward_command_controller/ForwardCommandController
    
#     forward_velocity_controllers:
#       type: forward_command_controller/ForwardCommandController

# joint_state_broadcaster:
#   ros__parameters:
#     extra_joints: 
#       - front_left_wheel
#       - front_right_wheel

# forward_position_controllers:
#   ros__parameters:
#     use_sim_time: true
#     joints:
#       - left_steering_hinge_wheel
#       - right_steering_hinge_wheel
#     interface_name: position
#     command_interface: 
#       - position
#     state_interface:
#       - position
#       - velocity
#       - effort

# forward_velocity_controllers:
#   ros__parameters:
#     use_sim_time: true
#     joints: 
#       - rear_left_wheel
#       - rear_right_wheel
#     interface_name: velocity
#     command_interface: 
#       - velocity
#     state_interface:
#       - position
#       - velocity
#       - effort

controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    position_controllers:
      type: forward_command_controller/ForwardCommandController
    
    velocity_controllers:
      type: forward_command_controller/ForwardCommandController

# joint_state_broadcaster:
#   ros__parameters:
#     extra_joints: 
#       - front_left_wheel
#       - front_right_wheel

position_controllers:
  ros__parameters:
    use_sim_time: true
    joints:
      - left_steer
      - right_steer 
    interface_name: position
    command_interface: 
      - position
    state_interface:
      - velocity
      - effort

velocity_controllers:
  ros__parameters:
    use_sim_time: true
    joints: 
      - left_rear_wheel
      - right_rear_wheel
    interface_name: velocity
    command_interface: 
      - velocity
    state_interface:
      - velocity
      - effort

# controller_manager:
#   ros__parameters:
#     update_rate: 100  # Hz

#     joint_state_broadcaster:
#       type: joint_state_broadcaster/JointStateBroadcaster

#     joint_trajectory_position_controller:
#       type: joint_trajectory_controller/JointTrajectoryController

#     position_controller:
#       type: position_controllers/JointGroupPositionController
    
#     velocity_controllers:
#       type: velocity_controllers/JointGroupVelocityController

# velocity_controllers:
#   ros__parameters:
#     joints: 
#       - left_joint_f
#       - right_joint_f
#       - left_joint_b
#       - right_joint_b
#     command_interface: 
#       - velocity
#     state_interface: 
#       - velocity
#       - effort

# position_controller:
#   ros__parameters:
#     joints:
#       - left_joint_s
#       - right_joint_s
#     command_interface: 
#       - position
#     state_interface: 
#       - velocity
#       - effort


forward_position_controller:
  ros__parameters:
    joints:
      - left_steer
      - right_steer 
      - left_front_wheel
      - right_front_wheel
      - left_rear_wheel
      - right_rear_wheel
    interface_name: position