controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    position_controllers:
      type: forward_command_controller/ForwardCommandController
    
    velocity_controllers:
      type: forward_command_controller/ForwardCommandController

joint_state_broadcaster:
  ros__parameters:
    publish_rate: 100  # Hz
    use_sim_time: true

position_controllers:
  ros__parameters:
    use_sim_time: true
    joints:
      - left_steer
      - right_steer 
    interface_name: position
    command_interface: 
      - position
    state_interface:
      - position
      - velocity
      - effort

velocity_controllers:
  ros__parameters:
    use_sim_time: true
    joints: 
      - left_rear_wheel
      - right_rear_wheel
    interface_name: velocity
    command_interface: 
      - velocity
    state_interface:
      - position
      - velocity
      - effort