controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controllers:
      type: forward_command_controller/ForwardCommandController
    
    forward_velocity_controllers:
      type: forward_command_controller/ForwardCommandController

forward_position_controllers:
  ros__parameters:
    use_sim_time: true
    joints:
      - left_steering_hinge_wheel
      - right_steering_hinge_wheel
    interface_name: position
    command_interface: 
      - position
    state_interface:
      - position
      - velocity
      - effort

forward_velocity_controllers:
  ros__parameters:
    use_sim_time: true
    joints: 
      - rear_left_wheel
      - rear_right_wheel
    interface_name: velocity
    command_interface: 
      - velocity
    state_interface:
      - position
      - velocity
      - effort
