<?xml version="1.0"?>

<!-- add xmlns:macro="link" to use xacro extension -->
<robot name="robot" xmlns:xacro="http://www.ros.org/wiki/xacro">  

    <!-- Include -->
    <xacro:include filename="inertials.xacro" />

    <!-- Define constant variables using xacro -->
    <xacro:property name="base_length" value="0.2" />
    <xacro:property name="base_width" value="0.13" />
    <xacro:property name="base_height" value="0.1" />
    <xacro:property name="wheel_radius" value="0.045" />
    <xacro:property name="wheel_length" value="0.01" />
    <xacro:property name="robot_namespace" value="/ackrobot"/>

    <material name="red">
        <color rgba="1 0 0 1"/> 
    </material>

    <material name="orange">
        <color rgba="1 0.6 0 1" />
    </material>

    <material name="grey">
        <color rgba="0.5 0.5 0.5 1" />
    </material>

    <material name="invisible">
        <color rgba="0.0 0.0 0.0 0.0"/>
    </material>

    <link name="base_footprint" />

    <!-- Chassis -->
    <link name="chassis">
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height - (wheel_radius / 2)}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
        </collision>
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height - (wheel_radius / 2)}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
            <material name="grey" />
        </visual>
        <xacro:inertial_box mass="2.0" x="${base_length}" y="${base_width}" z="${base_height - (wheel_radius / 2)}">
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <!-- rear Right Wheel -->
    <link name="rear_right_wheel_link">
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" /> 
        </collision>
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" /> 
            <material name="orange" />
        </visual>
        <xacro:inertial_cylinder mass="0.25" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    
    <!-- rear Left Wheel -->
    <link name="rear_left_wheel_link">
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
        </collision>
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            <material name="orange" />
        </visual>
    </link>

    <!-- Virtual Rear Wheel -->
    <link name="virtual_rear_wheel">
        <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2}"/>
        <geometry>
            <cylinder length="0.01" radius="${wheel_radius}"/>
        </geometry>
        <material name="invisible"/>
        </visual>
    </link>

    <!-- Front Right Wheel -->
    <link name="front_right_wheel_link">
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
        </collision>
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            <material name="orange" />
        </visual>
        <xacro:inertial_cylinder mass="0.25" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- Front Left Wheel -->
    <link name="front_left_wheel_link">
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
        </collision>
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            <material name="orange" />
        </visual>
        <xacro:inertial_cylinder mass="0.25" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    
    <!-- Virtual Front Wheel -->
    <link name="virtual_front_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2}"/>
            <geometry>
            <cylinder length="0.01" radius="${wheel_radius}"/>
            </geometry>
            <material name="invisible"/>
        </visual>
        <xacro:inertial_cylinder mass="0.0000001" length="0.01" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 ${pi / 2.0}"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- Joints -->
    <joint name="footprint_chassis_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="chassis" />
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" /> 
        <axis xyz="0 0 0" />
    </joint>

    <joint name="virtual_front_wheel_joint" type="revolute">
      <parent link="chassis"/>
      <child link="virtual_front_wheel"/>
      <origin xyz="${base_length/2} 0 0" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <limit lower="-0.4" upper="0.4" effort="100.0" velocity="0.0"/>
      <dynamics damping="0.2"/>
        <gazebo>
            <disable_physics>true</disable_physics>
        </gazebo>
    </joint>

    <joint name="virtual_rear_wheel_joint" type="continuous">
      <parent link="chassis"/>
      <child link="virtual_rear_wheel"/>
      <origin xyz="-${base_length/2} 0 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit effort="100.0" velocity="100.0"/>
      <dynamics damping="0.2"/>
        <gazebo>
            <disable_physics>true</disable_physics>
        </gazebo>
    </joint>

    <joint name="base_rear_right_wheel_joint" type="continuous">
        <parent link="chassis" />
        <child link="rear_right_wheel_link" />
        <origin xyz="${-base_length / 2.0} ${-(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <limit effort="100.0" velocity="100.0"/>
        <dynamics damping="0.2"/>
        <mimic joint="virtual_rear_wheel_joint" multiplier="1.0" offset="0.0"/>
    </joint>

    <joint name="base_rear_left_wheel_joint" type="continuous">
        <parent link="chassis" />
        <child link="rear_left_wheel_link" />
        <origin xyz="${-base_length / 2.0} ${(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <limit effort="100.0" velocity="100.0"/>
        <dynamics damping="0.2"/>
        <mimic joint="virtual_rear_wheel_joint" multiplier="1.0" offset="0.0"/>
    </joint>

    <joint name="base_front_right_wheel_joint" type="continuous">
        <parent link="chassis" />
        <child link="front_right_wheel_link" />
        <origin xyz="${base_length/2} ${-(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 0   1" />
        <limit lower="-0.4" upper="0.4" effort="100.0" velocity="0.0"/>
        <dynamics damping="0.2"/>
        <mimic joint="virtual_front_wheel_joint" multiplier="1.0" offset="0.0"/>
    </joint>

    <joint name="base_front_left_wheel_joint" type="continuous">
        <parent link="chassis" />
        <child link="front_left_wheel_link" />
        <origin xyz="${base_length/2} ${(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 0 1" />
        <limit lower="-0.4" upper="0.4" effort="100.0" velocity="0.0"/>
        <dynamics damping="0.2"/>
        <mimic joint="virtual_front_wheel_joint" multiplier="1.0" offset="0.0"/>
    </joint>

    <!-- <transmission name="virtual_front_wheel_joint_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <actuator name="virtual_front_wheel_joint_motor">
        <mechanicalReduction>1</mechanicalReduction>
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </actuator>
      <joint name="virtual_front_wheel_joint">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </joint>
    </transmission> 

    <transmission name="virtual_rear_wheel_joint_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <actuator name="virtual_rear_wheel_joint_motor">
        <mechanicalReduction>1</mechanicalReduction>
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      </actuator>
      <joint name="virtual_rear_wheel_joint">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      </joint>
    </transmission> -->

</robot>
