<?xml version="1.0"?>

<!-- add xmlns:macro="link" to use xacro extension -->
<robot name="robot" xmlns:xacro="http://www.ros.org/wiki/xacro">  

    <!-- Define constant variables using xacro -->
    <xacro:property name="base_length" value="0.2" />
    <xacro:property name="base_width" value="0.13" />
    <xacro:property name="base_height" value="0.1" />
    <xacro:property name="wheel_radius" value="0.045" />
    <xacro:property name="wheel_length" value="0.01" />

    <material name="red">
        <color rgba="1 0 0 1"/> 
    </material>

    <material name="orange">
        <color rgba="1 0.6 0 1" />
    </material>

    <material name="grey">
        <color rgba="0.5 0.5 0.5 1" />
    </material>

    <link name="footprint_link" />

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
            <material name="red" />
        </visual>
    </link>

    <!-- Back Right Wheel -->
    <link name="back_right_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" /> 
            <material name="orange" />
        </visual>
    </link>

    <!-- Back Left Wheel -->
    <link name="back_left_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            <material name="grey" />
        </visual>
    </link>

    <!-- Front Right Wheel -->
    <link name="front_right_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            <material name="orange" />
        </visual>
    </link>

    <!-- Front Left Wheel -->
    <link name="front_left_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            <material name="grey" />
        </visual>
    </link>

    <!-- Joints -->
    <joint name="footprint_base_joint" type="fixed">
        <parent link="footprint_link" />
        <child link="base_link" />
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" /> 
        <axis xyz="0 0 0" />
    </joint>

    <joint name="base_back_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="back_right_wheel_link" />
        <origin xyz="${-base_length / 4.0} ${-(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_back_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="back_left_wheel_link" />
        <origin xyz="${-base_length / 4.0} ${(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_front_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="front_right_wheel_link" />
        <origin xyz="${base_length / 4.0} ${-(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_front_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="front_left_wheel_link" />
        <origin xyz="${base_length / 4.0} ${(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

</robot>
